# -*- coding: utf-8 -*-
"""Defending.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EOPkafITPt3Yg2y9jJjkA3_qlG5tY0hh
"""

import requests
import pandas as pd

url = 'https://fbref.com/en/comps/Big5/2022-2023/defense/players/2022-2023-Big-5-European-Leagues-Stats'
defense_22_23 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_defense'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2021-2022/defense/players/2021-2022-Big-5-European-Leagues-Stats'
defense_21_22 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_defense'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2020-2021/defense/players/2020-2021-Big-5-European-Leagues-Stats'
defense_20_21 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_defense'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2019-2020/defense/players/2019-2020-Big-5-European-Leagues-Stats'
defense_19_20 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_defense'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2018-2019/defense/players/2018-2019-Big-5-European-Leagues-Stats'
defense_18_19 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_defense'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2017-2018/defense/players/2017-2018-Big-5-European-Leagues-Stats'
defense_17_18 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_defense'}
)[0]

defense_dataframes_list = [defense_22_23, defense_21_22, defense_20_21, defense_19_20, defense_18_19, defense_17_18]
count = 22
for dataframe in defense_dataframes_list:
  if 'Year' in dataframe.columns:
    dataframe.drop('Year', axis=1, inplace=True)
  else:
    dataframe['Year'] = count
    count = count - 1

combined_def = pd.concat(defense_dataframes_list, ignore_index=True)
# Drop columns with 'Per 90 Minutes'
combined_def = combined_def.loc[:, ~combined_def.columns.get_level_values(0).str.startswith('Per 90 Minutes')]

# Rename columns by keeping the second level as headers
combined_def.columns = combined_def.columns.droplevel(0)

#drop the matches column
combined_def = combined_def.drop(columns=combined_def.columns[-2])

# Rename the last column header to 'Year'
combined_def = combined_def.rename(columns={combined_def.columns[-1]: 'Year'})
combined_def = combined_def[['Player', 'Year', 'Tkl+Int']]
combined_def