# -*- coding: utf-8 -*-
"""GCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZYKWGHzo5h5ezl85NIjPt3T79MBTQaZ
"""

import requests
import pandas as pd

url = 'https://fbref.com/en/comps/Big5/2022-2023/gca/players/2022-2023-Big-5-European-Leagues-Stats'
gca_22_23 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_gca'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2021-2022/gca/players/2021-2022-Big-5-European-Leagues-Stats'
gca_21_22 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_gca'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2020-2021/gca/players/2020-2021-Big-5-European-Leagues-Stats'
gca_20_21 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_gca'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2019-2020/gca/players/2019-2020-Big-5-European-Leagues-Stats'
gca_19_20 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_gca'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2018-2019/gca/players/2018-2019-Big-5-European-Leagues-Stats'
gca_18_19 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_gca'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2017-2018/gca/players/2017-2018-Big-5-European-Leagues-Stats'
gca_17_18 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_gca'}
)[0]

gca_dataframes_list = [gca_22_23, gca_21_22, gca_20_21, gca_19_20, gca_18_19, gca_17_18]
count = 22
for dataframe in gca_dataframes_list:
  if 'Year' in dataframe.columns:
    dataframe.drop('Year', axis=1, inplace=True)
  else:
    dataframe['Year'] = count
    count = count - 1

combined_gca = pd.concat(gca_dataframes_list, ignore_index=True)
# Drop columns with 'Per 90 Minutes'
combined_gca = combined_gca.loc[:, ~combined_gca.columns.get_level_values(0).str.startswith('Per 90 Minutes')]

# Rename columns by keeping the second level as headers
combined_gca.columns = combined_gca.columns.droplevel(0)

#drop the matches column
combined_gca = combined_gca.drop(columns=combined_gca.columns[-2])

# Rename the last column header to 'Year'
combined_gca = combined_gca.rename(columns={combined_gca.columns[-1]: 'Year'})
combined_gca = combined_gca[['Player', 'Year', 'SCA', 'GCA']]
combined_gca