# -*- coding: utf-8 -*-
"""Passing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xecdZRVh-fNBv4KZ0hGyT4O5vbJ8KuHo
"""

import requests
import pandas as pd

url = 'https://fbref.com/en/comps/Big5/2022-2023/passing/players/2022-2023-Big-5-European-Leagues-Stats'
passing_22_23 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_passing'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2021-2022/passing/players/2021-2022-Big-5-European-Leagues-Stats'
passing_21_22 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_passing'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2020-2021/passing/players/2020-2021-Big-5-European-Leagues-Stats'
passing_20_21 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_passing'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2019-2020/passing/players/2019-2020-Big-5-European-Leagues-Stats'
passing_19_20 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_passing'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2018-2019/passing/players/2018-2019-Big-5-European-Leagues-Stats'
passing_18_19 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_passing'}
)[0]

url = 'https://fbref.com/en/comps/Big5/2017-2018/passing/players/2017-2018-Big-5-European-Leagues-Stats'
passing_17_18 = pd.read_html(
    requests.get(url).text.replace('<!--','').replace('-->','')
    ,attrs={'id':'stats_passing'}
)[0]

passing_dataframes_list = [passing_22_23, passing_21_22, passing_20_21, passing_19_20, passing_18_19, passing_17_18]
count = 22
for dataframe in passing_dataframes_list:
  if 'Year' in dataframe.columns:
    dataframe.drop('Year', axis=1, inplace=True)
  else:
    dataframe['Year'] = count
    count = count - 1

combined_passing = pd.concat(passing_dataframes_list, ignore_index=True)
# Drop columns with 'Per 90 Minutes'
combined_passing = combined_passing.loc[:, ~combined_passing.columns.get_level_values(0).str.startswith('Per 90 Minutes')]

# Rename columns by keeping the second level as headers
combined_passing.columns = combined_passing.columns.droplevel(0)

#drop the matches column
combined_passing = combined_passing.drop(columns=combined_passing.columns[-2])

# Rename the last column header to 'Year'
combined_passing = combined_passing.rename(columns={combined_passing.columns[-1]: 'Year'})
combined_passing = combined_passing[['1/3', 'PPA']]
combined_passing