# -*- coding: utf-8 -*-
"""merging_and_positions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gEkpK_MlG7DRUAvO_Lq-njMXAOjGcohK
"""

import pandas as pd

all_stats = pd.merge(all_stats, combined_gca, left_index=True, right_index=True)
all_stats = all_stats.drop(columns=['Player_y', 'Year_y']).rename(columns={'Player_x':'Player', 'Year_x':'Year'})
all_stats = pd.merge(all_stats, combined_def, left_index=True, right_index=True)
all_stats = pd.merge(all_stats, combined_passing, left_index=True, right_index=True)
all_stats = all_stats.sort_values(by=['Player', 'Year'], ascending = [True, True])
all_stats = all_stats.reset_index().drop(columns='index')
all_stats = all_stats.drop(columns=['npxG', 'npxG+xAG', 'Starts'])

forward_stats = all_stats[all_stats['Pos']=='FW'].reset_index(drop=True)

midfield_stats = all_stats[all_stats['Pos']=='MF'].dropna().reset_index(drop=True)

defense_stats = all_stats[all_stats['Pos']=='DF'].dropna().reset_index(drop=True)